services:
  - type: web
    name: payfornothingbot
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: PAYFORNOTHING_BOT_TOKEN
        sync: false
      - key: PAYFORNOTHING_CARD_NUMBER
        sync: false
      - key: PAYFORNOTHING_ADMIN_SECRET
        sync: false
      - key: PAYFORNOTHING_SUPPORT_CONTACT
        value: "@A777MP99"
